variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.kittmedia.com:wordpress/deploy-script.git
    - chmod +x deploy-script/*.sh


stages:
    - test
    - production

upload_zip_updateserver:
    stage: production

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_PRODUCTION -d $DEPLOY_PATH -h $DEPLOY_SERVER -z impressum

    only:
        - tags

    variables:
        DEPLOY_PATH: /var/www/wp-update-server/packages
        DEPLOY_SERVER: dagobah.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_PRODUCTION

upload_zip_wordpress:
    stage: production

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_PRODUCTION -d $DEPLOY_PATH -h $DEPLOY_SERVER -z impressum-plus

    only:
        - tags

    variables:
        DEPLOY_PATH: /var/www/epiphyt/wp-content/uploads/products/impressum-plus-fscw74q8ilntfz7arltz4a8tsa
        DEPLOY_SERVER: dagobah.kittmedia.com

        # GitLab project variables:
        # - SSH_USER_PRODUCTION