variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.kittmedia.com:wordpress/deploy-script.git
    - chmod +x deploy-script/*.sh

stages:
    - production
    - test

upload_svn:
    stage: production

    script:
        - cd deploy-script
        - ./deploy.sh --svn https://plugins.svn.wordpress.org/impressum

    only:
        - tags
