name: CI

on: [pull_request, push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Composer dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 5.6
        version: 2.2
    - name: Run PHPUnit
      uses: php-actions/phpunit@v4
      with:
        configuration: phpunit.xml
        php_version: 8.3
